trigger:
  branches:
    include:
      - main
  paths:
    include:
      - server
  

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        # Install JDK 21
        sudo apt update
        sudo apt install -y openjdk-21-jdk
        
        # Set JAVA_HOME environment variable
        export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
        export PATH=$JAVA_HOME/bin:$PATH

        # Verify installation
        java -version
      displayName: Install JDK 21

    - script: |
        # Install Maven
        sudo apt install -y maven
        
        # Verify installation
        mvn -version
      displayName: Install Maven

    - checkout: self

    - task: Maven@4
      inputs:
        mavenPomFile: 'server/pom.xml'
        options: '-DskipTests'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
      displayName: Build Spring Boot App
        
    - task: CopyFiles@2
      inputs:
        SourceFolder: 'server/target'
        Contents: 'app.jar'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
      displayName: Copy app.jar to Artifacts Directory
         
    - task: CopyFiles@2
      inputs:
        SourceFolder: 'server'
        Contents: 'Dockerfile'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
      displayName: Copy Dockerfile to Artifacts Directory
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/app.jar'
        ArtifactName: 'drop'
        publishLocation: 'Container'
      displayName: Publish app.jar to Artifacts

- stage: Deploy
  jobs:
  - job: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'PFE ACR'
        repository: 'spring-server'
        command: 'buildAndPush'
        Dockerfile: 'server/Dockerfile'
        tags: 'latest'
        arguments: '--build-arg JAR_FILE=$(Build.ArtifactStagingDirectory)/app.jar'
      displayName: Build and Push Server Docker image to ACR
