trigger:
  - main

pool:
  name: 'AzurePool'

steps:
  - script: |
      # Install JDK 21
      sudo apt update
      sudo apt install -y openjdk-21-jdk
      
      # Set JAVA_HOME environment variable
      export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
      export PATH=$JAVA_HOME/bin:$PATH

      # Verify installation
      java -version

  - script: |
      # Install Maven
      sudo apt install -y maven
      
      # Verify installation
      mvn -version

  - checkout: self

  - task: Maven@4
    inputs:
      mavenPomFile: 'server/pom.xml'
      options: '-DskipTests'
      publishJUnitResults: false
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false
      
  - task: CopyFiles@2
    inputs:
      SourceFolder: 'server/target'
      Contents: 'app.jar'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
       
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/app.jar'
      ArtifactName: 'drop'
      publishLocation: 'Container'
  
  - task: DockerInstaller@0
    inputs:
      dockerVersion: '17.09.0-ce'
  
  - script: sudo apt -y install docker.io
  
  - task: Docker@2
    inputs:
      containerRegistry: 'PFE ACR'
      repository: 'spring-server'
      command: 'build'
      Dockerfile: 'server/Dockerfile'
      arguments: '--build-arg JAR_FILE=$(Build.ArtifactStagingDirectory)/app.jar'
  
  - task: Docker@2
    inputs:
      containerRegistry: 'PFE ACR'
      repository: 'spring-server'
      command: 'push'