trigger:
  - main

pool:
  name: 'AzurePool'

steps:
  - script: |
      # Install JDK 21
      sudo apt update
      sudo apt install -y openjdk-17-jdk
      
      # Set JAVA_HOME environment variable
      export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
      export PATH=$JAVA_HOME/bin:$PATH

      # Verify installation
      java -version

  - script: |
      # Install Maven
      sudo apt install -y maven
      
      # Verify installation
      mvn -version

  - checkout: self

  - script: |
      # Build the Spring Boot application
      cd server
      mvn clean package
    displayName: 'Build Spring Boot App'