trigger:
  branches:
    include:
      - main
  paths:
    include:
      - server
  

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:

    - checkout: self
  
    - task: SonarQubePrepare@5
      inputs:
        SonarQube: 'PfeSonar'
        scannerMode: 'Other'
        extraProperties: |
          # Additional properties that will be passed to the scanner,
          # Put one key=value per line, example:
          # sonar.exclusions=**/*.bin
          sonar.projectKey=PFE_DevOps_PFE_37595dbe-4f5e-433f-a397-b949cb8d1a58
          sonar.projectName=PFE

    - task: Maven@4
      inputs:
        mavenPomFile: 'server/pom.xml'
        options: '-DskipTests'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.21'
        jdkArchitectureOption: 'x64'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
      displayName: Build Spring Boot App
        
    - task: SonarQubeAnalyze@5
      inputs:
        jdkversion: 'JAVA_HOME_21_X64'
      
    - task: SonarQubePublish@5
      inputs:
        pollingTimeoutSec: '300'
    - task: CopyFiles@2
      inputs:
        SourceFolder: 'server/target'
        Contents: 'app.jar'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
      displayName: Copy app.jar to Artifacts Directory
         
    - task: CopyFiles@2
      inputs:
        SourceFolder: 'server'
        Contents: 'Dockerfile'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
      displayName: Copy Dockerfile to Artifacts Directory
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/app.jar'
        ArtifactName: 'drop'
        publishLocation: 'Container'
      displayName: Publish app.jar to Artifacts

- stage: Deploy
  jobs:
  - job: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'azureDevOpsStage'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az acr login --name $(acrDisplayName)'
      displayName: Azure CLI Login to ACR

    - checkout: self
    
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'specific'
        itemPattern: 'drop/**'
        downloadPath: '$(System.ArtifactsDirectory)'
        cleanDestinationFolder: true
      
    - task: CopyFiles@2
      inputs:
        SourceFolder: 'server'
        Contents: 'Dockerfile'
        TargetFolder: '$(System.ArtifactsDirectory)'

    - script: |
        # Build Docker image
        docker build -t spring-server $(System.ArtifactsDirectory)
      displayName: Build Docker image

    - script: |
        # Tag Docker image
        docker tag spring-server $(acr-name)/spring-server:latest
      displayName: Tag Docker image

    - script: |
        # Push Docker image to Azure Container Registry
        docker push $(acr-name)/spring-server:latest
      displayName: Push Docker image to ACR

