trigger:

  - master

pool:
  name : "AzurePool"

steps:
  - task: Maven@3
    displayName: Build with Maven
    inputs:
      mavenPomFile: "server/pom.xml"
      mavenOptions: "-Xmx3072m"
      javaHomeOption: "JDKVersion"
      jdkVersionOption: "1.17"
      jdkArchitectureOption: "x64"
      publishJUnitResults: false
      goals: "package"