trigger:
  branches:
    include:
      - main
  paths:
    include:
      - client
  


stages:
- stage: CI
  jobs:
  - job: CI
    pool:
      vmImage: 'ubuntu-latest'
    variables:
    - group: ACRGroup
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'azureDevOpsStage'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az acr login --name $(acrDisplayName)'
      displayName: Azure CLI Login to ACR

    - checkout: self

    - script: |
        # Build Docker image
        docker build -t react-client ./client
      displayName: Build Docker image

    - script: |
        # Tag Docker image
        docker tag react-client $(acr-name)/react-client:$(Build.BuildId)
      displayName: Tag Docker image

    - script: |
        # Push Docker image to Azure Container Registry
        docker push $(acr-name)/react-client:$(Build.BuildId)
      displayName: Push Docker image to ACR

- stage: CD
  jobs:
  - job: CD
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      imageTag: '$(Build.BuildId)'
      acrName: '$(acr-name)' 
    steps:
    - checkout: self
    
    - task: KubectlInstaller@0
      inputs:
        kubectlVersion: 'latest'
    - task: replacetokens@6
      inputs:
        root: 'k8s'
        sources: '**/*.*'
        tokenPattern: 'azpipelines'
        missingVarLog: 'error'
    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'PFE AKS'
        command: 'apply'
        arguments: '-f ./k8s/client'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'
