apiVersion: v1
kind: Service
metadata:
  name: client-service
  labels:
    app: react-client
spec:
  selector:
    app: react-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
