apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-client
  labels:
    app: react-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-client
  template:
    metadata:
      labels:
        app: react-client
    spec:
      containers:
      - name: react-client
        image: your_registry/react-client:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
