#deploy pfeacr.azurecr.io/spring-server:41 here   
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-server
  labels:
    app: spring-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-server
  template:
    metadata:
      labels:
        app: spring-server
    spec:
      containers:
      - name: spring-server
        image: pfeacrdevops.azurecr.io/spring-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        envFrom:
        - secretRef:
            name: spring-server-secrets
  