apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-client
  labels:
    app: react-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-client
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: react-client
    spec:
      containers:
      - name: react-client
        image: $(acrName)/react-client:$(imageTag)
        imagePullPolicy: Always
        ports:
        - containerPort: 80
