#deploy pfeacr.azurecr.io/spring-server:41 here   
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-server
  labels:
    app: spring-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: spring-server
    spec:
      containers:
      - name: spring-server
        image: $(acrName)/spring-server:$(imageTag)
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        envFrom:
        - secretRef:
            name: spring-server-secrets
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 20

  